export default function Head({params}) {
  return (
    <>
      <title>Al-Quran </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1705/1705004.png" />
    </>
  )
}
